name: moe-caption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pip:
      - torch
      - transformers
      - sentencepiece
      - spacy
      - datasets